version: 0.0
os: linux
files:
  - source: /ke-notification.war
    destination: /opt/tomcat8/webapps/
hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
  ApplicationStart:
    - location: start_server.sh
      timeout: 36000
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: MonitorService.sh
      timeout: 36000
      runas: root